version: "3.9"

services:

  www:
    container_name: 'pds-portal-legacy-apache'
    build:
      dockerfile: Dockerfile
      context: ./apache
    image: 'pds-portal-legacy-apache'
    ports:
      - '80:80'
    restart: on-failure
    volumes:
      - "./apache/var/www/portal-legacy:/var/www/portal-legacy"
      - "./apache/var/log/apache2:/var/log/apache2"